/**
 * Turn the FDC-verified pipeline output (spike-results.json) into the app's
 * recipe catalogue — real computed macros, food tokens derived from the drafts.
 * Only recipes whose ingredients ALL resolved (macros complete) are emitted, so
 * the catalogue never ships understated numbers.
 *
 *   npx tsx scripts/gen-app-catalogue.ts
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const pkgDir = dirname(dirname(fileURLToPath(import.meta.url)));
const resultsPath = join(pkgDir, 'data', 'spike-results.json');
const draftDir = join(pkgDir, 'data', 'recipes-draft');
const outPath = join(pkgDir, '..', '..', 'app', 'src', 'data', 'catalogue.generated.ts');

// staples are assumed on-hand (§7) → not food tokens for cookability
const STAPLES = new Set(['salt', 'pepper', 'black pepper', 'white pepper', 'oil', 'olive oil', 'vegetable oil', 'sunflower oil', 'cooking oil', 'sesame oil', 'water', 'flour', 'plain flour', 'cornflour', 'sugar', 'brown sugar', 'stock', 'stock cube', 'chicken stock', 'vegetable stock', 'beef stock', 'spices', 'seasoning', 'baking powder', 'vinegar']);

const tokenOf = (name: string) => name.toLowerCase().split(',')[0]!.trim();

interface Draft { id: string; name: string; cuisine: string; slotAffinity: string[]; effort: string; steps: string[]; ingredients: Array<{ name: string; qty_g: number }> }

if (!existsSync(resultsPath)) { console.error(`No ${resultsPath}. Run "npm run spike" first.`); process.exit(1); }

// index drafts by id
const drafts = new Map<string, Draft>();
for (const f of readdirSync(draftDir).filter((f) => f.endsWith('.json'))) {
  try { const d = JSON.parse(readFileSync(join(draftDir, f), 'utf8')) as Draft; if (d?.id) drafts.set(d.id, d); } catch { /* skip */ }
}

const { results } = JSON.parse(readFileSync(resultsPath, 'utf8')) as { results: Array<{ result: { id: string | null; name: string | null; status: string; perServingRounded: { kcal: number; protein_g: number; carbs_g: number; fat_g: number } | null; allergens: string[]; reviewReasons: string[] } }> };

const usable = results
  .map((e) => e.result)
  .filter((r) => r.id && r.name && r.perServingRounded && r.perServingRounded.kcal > 60
    // ready, or needs-review ONLY for non-macro reasons (never when an ingredient didn't resolve)
    && (r.status === 'ready' || !r.reviewReasons.some((x) => /unresolved|hazard|rejected/i.test(x))));

const recipes = usable.map((r) => {
  const d = drafts.get(r.id!);
  const ps = r.perServingRounded!;
  const foodTokens = d ? [...new Set(d.ingredients.map((i) => tokenOf(i.name)).filter((t) => t.length > 1 && !STAPLES.has(t)))] : [];
  return {
    id: r.id!, name: r.name!,
    cuisine: d?.cuisine ?? 'British',
    slotAffinity: d?.slotAffinity ?? ['dinner'],
    effort: d?.effort ?? '15min',
    perServing: { kcal: Math.round(ps.kcal), protein_g: Math.round(ps.protein_g), carbs_g: Math.round(ps.carbs_g), fat_g: Math.round(ps.fat_g) },
    allergens: r.allergens,
    foodTokens,
    steps: d?.steps ?? [],
  };
});

const body = `// AUTO-GENERATED by packages/catalogue-pipeline/scripts/gen-app-catalogue.ts — do not edit.
// ${recipes.length} FDC-verified recipes (macros computed from USDA FDC, not authored).
import type { MenuSeedRecipe } from './menu-seed';

export const GENERATED: MenuSeedRecipe[] = ${JSON.stringify(recipes, null, 2)};
`;

writeFileSync(outPath, body);
console.log(`Wrote ${recipes.length} recipes → ${outPath}`);
const bySlot: Record<string, number> = {};
for (const r of recipes) for (const s of r.slotAffinity) bySlot[s] = (bySlot[s] ?? 0) + 1;
console.log('by slot:', JSON.stringify(bySlot));
const hiP = recipes.filter((r) => r.perServing.protein_g >= 30).length;
console.log(`high-protein (≥30g): ${hiP}`);
